image: maciejkrupowies/nativescript-ultim:latest

pipelines:
 branches:
   master:
     - step:
         script:
           - cd app/
           - npm install
           - tns build android --bundle
           - mv /opt/atlassian/pipelines/agent/build/platforms/android/app/build/outputs/apk/debug/app-debug.apk /opt/atlassian/pipelines/agent/build/bash_scripts/
           - cd /opt/atlassian/pipelines/agent/build/bash_scripts/ && curl https://tok_t15xap0q1grbcrfztj907bcfq0@api.appetize.io/v1/apps -F "file=@app-debug.apk" -F "platform=android" >> output.log
           - bash slack-webhook.sh
           
   blondel:
     - step:
         script:
           - cd app/
           - npm install
           - tns build android --bundle
           - mv /opt/atlassian/pipelines/agent/build/platforms/android/app/build/outputs/apk/debug/app-debug.apk /opt/atlassian/pipelines/agent/build/bash_scripts/
           - cd /opt/atlassian/pipelines/agent/build/bash_scripts/ && curl https://tok_t15xap0q1grbcrfztj907bcfq0@api.appetize.io/v1/apps -F "file=@app-debug.apk" -F "platform=android" >> output.log
           - bash slack-webhook.sh
